import { ResearchResults } from './ResearchResults'
import { ResearchMode, type ResearchScope } from './ResearchMode'
import { useCallback, useEffect, useRef, useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Plus, X, Columns2, PanelLeft, PanelRight, Send, ArrowLeft } from 'lucide-react'
import { toast } from 'sonner'
import api from '@/api/client'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Checkbox } from '@/components/ui/checkbox'
import { TooltipProvider } from '@/components/ui/tooltip'
import { PageLayout, PageHeader } from '@/components/shared/PageLayout'
import { ErrorState } from '@/components/shared/ErrorState'
import { Markdown } from '@/components/shared/Markdown'
import SegmentTabs from '@/components/shared/SegmentTabs'
import { citationComponents, linkifyCitations } from '@/components/chat/citations'
import type { ChatMessage } from '@/types'
import { StudyWorkspace } from './StudyPage'
import { type Annotation, errorMessage, useStudy } from './useStudy'
import { useProject, type StudyProject } from './useProjects'
import { ProjectMaterials } from './ProjectMaterials'

export default function ProjectPage(){const {id}=useParams();return <ProjectWorkspace key={id} id={Number(id)}/>}
function ProjectWorkspace({id}:{id:number}){
 const q=useProject(id),p=q.data,cache=useQueryClient(),[params,setParams]=useSearchParams()
 const [tabs,setTabs]=useState<number[]>(()=>{try{return JSON.parse(sessionStorage.getItem(`project-tabs-${id}`)||'[]')}catch{return []}})
 const [compare,setCompare]=useState<number|null>(null),[library,setLibrary]=useState(()=>window.innerWidth>1100),[adding,setAdding]=useState(false),[panel,setPanel]=useState('annotations'),[notesOpen,setNotesOpen]=useState(true)
 const [scopeOpen,setScopeOpen]=useState(()=>window.innerWidth>760)
 const [host,setHost]=useState<HTMLDivElement|null>(null),[sources,setSources]=useState<number[]>([]),[annotations,setAnnotations]=useState<Record<number,Annotation[]>>({}),[dirty,setDirty]=useState<Record<number,boolean>>({})
 const [research,setResearch]=useState<ResearchScope>('auto')
 const [question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[append,setAppend]=useState('')
 const request=useRef<{signature:string;key:string}|null>(null),initialized=useRef(false),chatRef=useRef<HTMLDivElement>(null)
 const active=Number(params.get('doc'))||tabs[0]||0
 const generating=p?.turns.some(t=>t.status==='pending')??false
 useEffect(()=>{const media=window.matchMedia('(max-width:760px)');const collapse=()=>{if(media.matches)setScopeOpen(false)};media.addEventListener('change',collapse);return()=>media.removeEventListener('change',collapse)},[])
 const onSelection=useCallback((sid:number,items:Annotation[])=>setAnnotations(prev=>({...prev,[sid]:items})),[])
 const onDirty=useCallback((sid:number,value:boolean)=>setDirty(prev=>prev[sid]===value?prev:{...prev,[sid]:value}),[])
 const conv=useQuery({queryKey:['spine','project-chat',p?.conversation_id],queryFn:async()=>(await api.get<{messages:ChatMessage[]}>(`/api/spine/conversations/${p!.conversation_id}`)).data,enabled:!!p?.conversation_id,refetchInterval:generating?1500:false})
 useEffect(()=>{if(p?.conversation_id)void cache.invalidateQueries({queryKey:['spine','project-chat',p.conversation_id]})},[p?.conversation_id,p?.turns.at(-1)?.status,cache])
 useEffect(()=>{if(p&&!initialized.current){const alive=p.documents.map(d=>d.id);setTabs(t=>{const valid=t.filter(i=>alive.includes(i));return valid.length?valid:alive.slice(0,1)});setSources(p.turns.some(t=>t.status==='complete')?[]:alive.slice(0,1));initialized.current=true}},[p])
 useEffect(()=>{if(active)setTabs(t=>t.includes(active)?t:[...t,active])},[active])
 useEffect(()=>{try{sessionStorage.setItem(`project-tabs-${id}`,JSON.stringify(tabs))}catch{/* UI storage only */}},[tabs,id])
 useEffect(()=>{if(panel==='chat')chatRef.current?.scrollTo({top:chatRef.current.scrollHeight})},[conv.data?.messages.length,panel])
 function open(sid:number){setParams(prev=>{prev.set('doc',String(sid));prev.delete('annotation');return prev},{replace:true})}
 function close(sid:number){if(dirty[sid]){toast('코멘트를 먼저 저장해 주세요.');return}const next=tabs.filter(x=>x!==sid);setTabs(next);if(active===sid){setParams(prev=>{prev.delete('annotation');if(next[0])prev.set('doc',String(next[0]));else prev.delete('doc');return prev},{replace:true})}if(compare===sid)setCompare(null)}
 async function reload(){await q.refetch();await cache.invalidateQueries({queryKey:['spine','study-projects']})}
 function prepare(sid:number,items:Annotation[],text:string){setAnnotations(prev=>({...prev,[sid]:items}));setSources([sid]);setQuestion(text);setPanel('chat')}
 async function send(){if(!p||busy||generating||!question.trim())return;if(Object.values(dirty).some(Boolean)){toast('작성 중인 코멘트를 먼저 저장해 주세요.');setPanel('annotations');return}const selected=sources.filter(sid=>p.documents.some(d=>d.id===sid));if(!selected.length&&!p.turns.some(t=>t.status==='complete')){toast('AI에 보낼 자료를 선택해 주세요.');return}
 const payload={question,research,context_mode:selected.length?'selection':'continue',sources:selected.map(study_id=>({study_id,annotations:(annotations[study_id]||[]).map(a=>({id:a.id,revision:a.revision}))}))};const signature=JSON.stringify(payload);if(request.current?.signature!==signature)request.current={signature,key:crypto.randomUUID()};setBusy(true)
 try{await api.post(`/api/spine/study-projects/${id}/ask`,{...payload,request_key:request.current.key});request.current=null;setQuestion('');setSources([]);await reload()}catch(e){toast.error(errorMessage(e))}finally{setBusy(false)}}
 if(q.isLoading)return <p className="p-6 text-sm">프로젝트를 불러오는 중…</p>
 if(q.isError||!p)return <ErrorState message="프로젝트를 불러올 수 없습니다." onRetry={()=>q.refetch()}/>
 const sourceDocs=p.documents.filter(d=>sources.includes(d.id))
 return <TooltipProvider><PageLayout header={<PageHeader title={p.title} description={`${p.documents.length}개 자료 · 함께 읽고 질문하는 스터디`} actions={<><Button size="sm" variant="ghost" asChild><Link to="/study"><ArrowLeft/>스터디 목록</Link></Button><Button size="sm" variant="outline" onClick={()=>setAdding(true)}><Plus/>자료 추가</Button></>}/> }>
 <div className="project-workspace" data-library={library} data-notes={notesOpen}>
  <div className="project-toolbar"><Button size="sm" variant="ghost" aria-pressed={library} onClick={()=>setLibrary(v=>!v)}><PanelLeft/>자료함</Button><Button size="sm" variant={compare?'secondary':'ghost'} disabled={p.documents.length<2} onClick={()=>{setCompare(compare?null:p.documents.find(d=>d.id!==active)?.id??null);if(!compare)setLibrary(false)}}><Columns2/>두 자료 비교</Button><span className="ml-auto text-caption text-muted-foreground">프로젝트별 주석 · 문서는 고정 보관</span><Button size="sm" variant="ghost" aria-pressed={notesOpen} aria-controls="project-panel" onClick={()=>setNotesOpen(v=>!v)}><PanelRight/>노트·AI 대화</Button></div>
  <div className="project-columns">
   {library&&<nav className="project-library" aria-label="프로젝트 자료함"><h2 className="text-sm font-semibold mb-3">함께 공부할 자료</h2>{p.documents.length?p.documents.map(d=><div className={`project-source ${active===d.id?'bg-muted':''}`} key={d.id}><button className="min-w-0 flex-1 text-left" onClick={()=>open(d.id)} aria-current={active===d.id?'page':undefined}><span className="text-caption text-muted-foreground">{d.source_type} · {d.published_at?.slice(0,10)||'발행일 미상'}</span><span className="block text-sm font-medium my-1 line-clamp-2">{d.title}</span><span className="text-caption text-muted-foreground">주석 {d.annotation_count}개</span></button><Button size="icon-sm" variant="ghost" aria-label={`${d.title} 프로젝트에서 제거`} onClick={async()=>{if(dirty[d.id]){toast('코멘트를 먼저 저장해 주세요.');return}try{await api.delete(`/api/spine/study-projects/${id}/documents/${d.id}`);close(d.id);setSources(s=>s.filter(x=>x!==d.id));await reload();toast('프로젝트에서 뺐습니다. 주석은 다시 추가하면 이어집니다.')}catch(e){toast.error(errorMessage(e))}}}><X/></Button></div>):<p className="text-sm text-muted-foreground">자료를 추가해 시작하세요.</p>}<Button className="mt-4 w-full" variant="outline" size="sm" onClick={()=>setAdding(true)}><Plus/>자료 추가</Button></nav>}
   <section className="project-desk" aria-label="읽기 책상"><div className="project-tabs" role="tablist" aria-label="펼쳐둔 자료">{tabs.map(sid=><div key={sid} className="flex shrink-0 items-center"><button role="tab" id={`project-tab-${sid}`} aria-controls={`project-document-${sid}`} tabIndex={active===sid?0:-1} onKeyDown={e=>{const index=tabs.indexOf(sid);const next=e.key==='ArrowRight'?tabs[(index+1)%tabs.length]:e.key==='ArrowLeft'?tabs[(index+tabs.length-1)%tabs.length]:e.key==='Home'?tabs[0]:e.key==='End'?tabs.at(-1):undefined;if(next){e.preventDefault();open(next);document.getElementById(`project-tab-${next}`)?.focus()}}} aria-selected={active===sid} className={`project-tab ${active===sid?'bg-muted text-foreground':''}`} onClick={()=>open(sid)}>{p.documents.find(d=>d.id===sid)?.title||'보관 자료'}</button><Button size="icon-sm" variant="ghost" aria-label={`자료 탭 ${sid} 닫기`} onClick={()=>close(sid)}><X/></Button></div>)}</div>
    {!active?<div className="p-8 text-sm text-muted-foreground">유튜브, 텔레그램, 블로그와 직접 쓴 메모를 한 책상에 펼쳐보세요.<Button className="mt-4 block" variant="outline" onClick={()=>setAdding(true)}>첫 자료 추가</Button></div>:<div className={`project-readers ${compare&&compare!==active?'is-comparing':''}`}><div className="project-primary">{[...new Set([...p.documents.map(d=>d.id),...tabs])].map(sid=><div key={sid} id={`project-document-${sid}`} role="tabpanel" aria-labelledby={`project-tab-${sid}`} hidden={sid!==active}><StudyWorkspace id={sid} embedded active={sid===active} unifiedNotes={p.documents.some(d=>d.id===sid)} noteHost={host} history={p.turns.flatMap(t=>t.context.sources.filter(source=>source.study_id===sid).flatMap(source=>source.annotations))} initialPicked={[]} onNotes={()=>setPanel('annotations')} onSelection={onSelection} onDirty={onDirty} onAsk={prepare}/></div>)}</div>{compare&&compare!==active&&<CompareReader id={compare} documents={p.documents} onChange={setCompare} onActivate={()=>{const previous=active;open(compare);setCompare(previous)}}/>}</div>}
   </section>
   <aside className="project-panel" id="project-panel" aria-label="프로젝트 학습 패널" hidden={!notesOpen}><div className="project-panel-tabs"><SegmentTabs tabs={[{value:'annotations',label:'노트'},{value:'chat',label:'AI 대화'}]} value={panel} onChange={setPanel}/></div>
    <div className="project-unified-notes" hidden={panel!=='annotations'}><ProjectNote project={p} append={append} onAppended={()=>setAppend('')} onSaved={reload}/><p className="px-4 py-2 text-caption text-muted-foreground">인용 카드의 문서 태그를 누르면 원문 위치로 이동합니다. 체크한 주석을 AI에 함께 보낼 수 있습니다.</p><div ref={setHost} className="project-annotation-host"/></div>
    {panel==='chat'&&<><div ref={chatRef} className="project-chat" aria-live="polite">{!conv.data?.messages.length&&<p className="text-sm text-muted-foreground py-4">자료별 관점과 발행 시점을 비교해 보세요. 문서는 옆에 펼쳐둔 채 질문할 수 있습니다.</p>}{conv.isError&&<Button variant="outline" onClick={()=>conv.refetch()}>대화 다시 불러오기</Button>}{conv.data?.messages.map((m,index)=><div className={`study-message ${m.role==='user'?'study-question':''}`} key={m.id}><p className="text-caption text-muted-foreground mb-2">{m.role==='user'?'나':'AI · 학습 도우미'}</p><Markdown components={citationComponents(m.citations??null)}>{linkifyCitations(m.content,m.citations??null)}</Markdown>{m.role==='assistant'&&<ResearchResults research={p.turns.find(t=>t.message_id===conv.data?.messages[index-1]?.id)?.context.research}/>}{m.role==='assistant'?<Button size="sm" variant="ghost" onClick={()=>{setAppend(m.content);setPanel('annotations')}}>노트에 가져오기</Button>:<details className="mt-2 text-caption"><summary>이 질문에 사용한 자료</summary>{p.turns.find(t=>t.message_id===m.id)?.context.sources.map(s=><div key={s.study_id} className="my-2"><button className="text-primary text-left" onClick={()=>open(s.study_id)}>{s.title}</button><p>{s.scope}</p>{s.annotations.map(a=><blockquote key={a.id} className="my-1">{a.exact}{a.comment&&<p>내 코멘트: {a.comment}</p>}</blockquote>)}</div>)}</details>}</div>)}{(busy||generating)&&<p role="status" className="text-sm text-muted-foreground">선택한 자료를 함께 읽고 답변하는 중…</p>}{p.turns.at(-1)?.error&&<p role="alert" className="text-sm text-destructive">{p.turns.at(-1)?.error}</p>}{p.turns.filter(t=>t.status==='pending'&&Date.now()-Date.parse(t.created_at.replace(' ','T')+'Z')>600000).map(t=><Button key={t.id} size="sm" variant="outline" onClick={async()=>{try{await api.post(`/api/spine/study-projects/${id}/turns/${t.id}/recover`);await reload()}catch(e){toast.error(errorMessage(e))}}}>멈춘 요청 정리</Button>)}</div>
    <div className="project-composer"><ResearchMode value={research} onChange={setResearch}/>{!sourceDocs.length&&p.turns.some(t=>t.status==='complete')&&<p className="text-caption mb-2">이전 대화 이어가기 · 자료와 주석 재첨부 없음</p>}<details open={scopeOpen} onToggle={e=>setScopeOpen(e.currentTarget.open)}><summary className="text-caption">함께 보낼 내용 · 자료 {sourceDocs.length}개 · 주석 {sourceDocs.reduce((n,d)=>n+(annotations[d.id]?.length||0),0)}개</summary><div className="flex flex-wrap gap-1 my-2"><Button size="sm" variant="ghost" onClick={()=>setSources(p.documents.some(d=>d.id===active)?[active]:[])}>현재 자료</Button><Button size="sm" variant="ghost" onClick={()=>setSources([...new Set([...tabs,...(compare?[compare]:[])])].filter(sid=>p.documents.some(d=>d.id===sid)))}>펼친 자료</Button><Button size="sm" variant="ghost" onClick={()=>setSources(p.documents.map(d=>d.id))}>전체 자료</Button></div><div className="project-scope">{p.documents.map(d=><div key={d.id} className="my-2"><label className="flex items-start gap-2 text-caption"><Checkbox aria-label={`AI에 포함 자료 ${d.id}`} checked={sources.includes(d.id)} onCheckedChange={v=>setSources(s=>v?[...s,d.id]:s.filter(x=>x!==d.id))}/><span>{d.title}<span className="block text-muted-foreground">{annotations[d.id]?.length?`선택 주석 ${annotations[d.id].length}개 · 저장 코멘트 포함`:d.body_length>16000?'본문 앞 16,000자':'본문 전체'}</span></span></label>{sources.includes(d.id)&&annotations[d.id]?.map(a=><p key={a.id} className="ml-6 mt-1 text-caption text-muted-foreground">{a.exact.slice(0,80)}{a.comment&&` · 내 코멘트: ${a.comment.slice(0,80)}`}</p>)}</div>)}</div><p className="text-caption text-muted-foreground mt-2">최대 자료 10개 · 질문에 따라 관련 자료 탐색과 웹 검증을 돕습니다.</p></details><Textarea className="mt-3" aria-label="프로젝트 질문" value={question} maxLength={4000} onChange={e=>setQuestion(e.target.value)} placeholder="어제와 오늘의 전망이 어떻게 달라졌어?" onKeyDown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();void send()}}}/><div className="flex justify-between items-center mt-2">{p.conversation_id?<Link className="text-caption text-muted-foreground" to={`/chat?id=${p.conversation_id}`}>대화 이력 ↗</Link>:<span className="text-caption text-muted-foreground">대화 이력에도 남습니다</span>}<Button size="sm" disabled={busy||generating||!question.trim()||(!sourceDocs.length&&!p.turns.some(t=>t.status==='complete'))||sourceDocs.length>10} onClick={send}><Send/>보내기</Button></div></div></>}
   </aside>
  </div>
 </div><ProjectMaterials pid={id} open={adding} onOpenChange={setAdding} onAdded={ids=>{void reload();setTabs(t=>[...new Set([...t,...ids])]);if(ids[0])open(ids[0])}}/>
 </PageLayout></TooltipProvider>
}
function CompareReader({id,documents,onChange,onActivate}:{id:number;documents:StudyProject['documents'];onChange:(id:number)=>void;onActivate:()=>void}){const q=useStudy(id);return <section className="project-compare" aria-label="비교 자료"><div className="flex items-center gap-2 p-2 border-b"><select aria-label="비교할 자료" className="min-w-0 flex-1 text-sm bg-card" value={id} onChange={e=>onChange(Number(e.target.value))}>{documents.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select><Button size="sm" variant="ghost" onClick={onActivate}>표시하며 읽기</Button></div><article className="p-5 overflow-auto"><p className="text-caption text-muted-foreground mb-4">비교용 읽기 · 표시하려면 ‘표시하며 읽기’로 전환하세요.</p>{q.isLoading?'불러오는 중…':q.isError?<Button onClick={()=>q.refetch()}>다시 불러오기</Button>:<div className="whitespace-pre-wrap text-sm leading-relaxed break-words">{q.data?.body}</div>}</article></section>}
function ProjectNote({project:p,append,onAppended,onSaved}:{project:StudyProject;append:string;onAppended:()=>void;onSaved:()=>Promise<void>}){
 const [title,setTitle]=useState(p.title),[note,setNote]=useState(p.note),[revision,setRevision]=useState(p.revision),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const dirty=title!==p.title||note!==p.note
 useEffect(()=>{if(append){setNote(n=>n+(n?'\n\n':'')+append);onAppended()}},[append,onAppended])
 useEffect(()=>{try{const saved=localStorage.getItem(`project-note-draft-${p.id}`);if(saved){const d=JSON.parse(saved);setTitle(d.title);setNote(d.note);setRevision(d.revision)}}catch{/* optional draft */}},[p.id])
 useEffect(()=>{try{if(dirty)localStorage.setItem(`project-note-draft-${p.id}`,JSON.stringify({title,note,revision}));else localStorage.removeItem(`project-note-draft-${p.id}`)}catch{/* explicit save still available */}},[title,note,revision,dirty,p.id])
 async function save(){setBusy(true);try{const {data}=await api.patch(`/api/spine/study-projects/${p.id}`,{title,note,revision});setRevision(data.revision);setError('');await onSaved();toast.success('노트를 저장했습니다.')}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 return <section className="p-4 space-y-3"><label className="block text-caption">프로젝트 이름<Input className="mt-1" value={title} maxLength={160} aria-label="프로젝트 이름 수정" onChange={e=>setTitle(e.target.value)}/></label><p className="text-caption text-muted-foreground">내가 채택한 이해와 남은 질문을 적어두세요. AI 답변을 가져온 뒤 직접 수정하고 저장합니다.</p><Textarea aria-label="노트 본문" className="min-h-24 text-sm" value={note} maxLength={100000} onChange={e=>setNote(e.target.value)} placeholder="자료를 읽으며 떠오른 생각이나 질문을 자유롭게 적어두세요"/><Button size="sm" disabled={busy||!dirty||!title.trim()} onClick={save}>{busy?'저장 중…':dirty?'노트 저장':'저장됨'}</Button>{dirty&&<p className="text-caption text-muted-foreground">저장 전 초안 · 이 브라우저에 임시 보관됩니다.</p>}{error&&<div role="alert" className="text-sm text-destructive">{error}<Button size="sm" variant="ghost" onClick={async()=>{try{const {data}=await api.get<StudyProject>(`/api/spine/study-projects/${p.id}`);setRevision(data.revision);await onSaved();setError('최신 서버 노트를 아래에서 비교한 뒤, 현재 초안을 저장할 수 있습니다.')}catch(e){setError(errorMessage(e))}}}>최신 내용 확인</Button><p className="text-caption">현재 서버 노트: {p.note}</p></div>}</section>
}
